# Generated by Django 5.0.2 on 2024-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_origianl_url_shortlink_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
